// The 23 screens: overlay content, camera shots, substeps, speaker notes.
// Copy is generated from talk/SCRIPT.md and talk/DESIGN.md; keep them in sync.

const C = {
  input: '#6ee7b7', exp: '#60a5fa', life: '#f59e0b', sdlc: '#f472b6',
  agent: '#38bdf8', cap: '#34d399', std: '#fbbf24', int: '#c084fc',
  know: '#22d3ee', dist: '#fb7185', infra: '#94a3b8', gov: '#ef4444',
  meas: '#10b981', outcome: '#facc15', ink: '#e6edf3',
};

export const ACTS = [
  'The Empty Lot', 'The Line', 'On & Under the Floor',
  'Beyond One Plant', 'The Invisible Systems', 'The Picture',
];

export const STEPS = [
  {
    act: 1, accent: C.know, kicker: 'Welcome',
    title: 'We are going to build a factory',
    qr: true,
    bullets: [
      'A Bill of Materials for the agentic SDLC, assembled live',
      'You leave with a parts list to hold your own org against',
    ],
    notes: [
      'Welcome. I am Roman Gurevitch, Principal Software Engineer at Mantel.',
      'Tonight we build a factory, live, piece by piece.',
      'You leave with a complete parts list for agentic engineering, and a way to decide how much of it your org needs.',
    ],
    cam: { pos: [0, -5, 44], target: [0, -4.5, -6] },
  },
  {
    act: 1, accent: C.infra, kicker: 'The problem',
    title: 'Easy to start, hard to hold together',
    bullets: [
      'Everyone is adopting, and a coding agent takes an afternoon to set up',
      'Models, tools, patterns change faster than plans can',
      'The hard part is common ways of working, reusable components, and evolving them over time',
    ],
    notes: [
      'Everyone in this room is adopting agentic engineering, or trying to.',
      'Starting is the easy part; a coding agent takes an afternoon. Watch the ground under each quick start. It never stops moving.',
      'Models, tools, and patterns change month to month. Hard to plan against, hard to standardize on.',
      'So the hard part is not starting. It is common ways of working, reusable components, and evolving them as everything shifts.',
    ],
    cam: { pos: [16, -3, 22], target: [0, -10, -2] },
  },
  {
    act: 1, accent: C.know, kicker: 'The idea',
    title: 'A Bill of Materials',
    bullets: [
      'Manufacturing solved this a century ago. Every part named, composed, load-bearing.',
      'The whole agentic SDLC on one page; you cannot assess your org against a list you have never seen',
      'Every component keeps its color for the whole talk, in the labels, the dots, the full plant',
      'The rest of the talk breaks this page apart, piece by piece',
    ],
    notes: [
      'Manufacturing solved this a century ago with the Bill of Materials. Every part named, how parts compose, what is load-bearing.',
      'Here is the whole agentic SDLC on one page. It looks complex. That is exactly the point. You cannot hold your org against a list you have never seen.',
      'Every component keeps one color for the rest of the talk. The labels, the dots at the bottom right, the full plant at the end; the colors are the map.',
      'The rest of the talk breaks this page apart, piece by piece. Not a vendor pitch, not a maturity model.',
    ],
    cam: { pos: [6, 0.5, 52], target: [6, -0.4, 26] },
  },
  {
    act: 2, accent: C.life, kicker: 'The frame',
    title: 'First, the Head Office',
    bullets: [
      'Leadership decides what gets built and how: requirements, priorities, risk appetite',
      'Technical and non-technical leadership together, not an engineering side project',
      'They create the factory rather than run it: choose the workflows, define the definition of done, set the baseline',
    ],
    notes: [
      'One orientation before we build: work flows front to back, in at the intake wall, out at the shipping dock. Everything else hangs off that line.',
      'Before any machinery, the Head Office rises as the TOP LEVEL, a deck above where the factory will stand.',
      'Inside it sits the business, technical and non-technical leadership. They define the requirements and what needs to be built.',
      'They are not going to run this factory. They are going to CREATE it: choose each team’s workflow, define the definition of done, set the mandatory baseline. Every component tonight is a decision made up here.',
    ],
    cam: { pos: [-36, 20, 0], target: [-14, 13.5, -27] },
  },
  {
    act: 2, accent: C.input, kicker: 'Continuous Inputs',
    title: 'The intake gate',
    bullets: [
      'Business goals · leadership direction · user feedback · telemetry & incidents · market & regulation',
      'Real inputs fall continuously: a Sev-2, an NPS dip, a CPS 230 update',
      'Each input starts a product, and every layer it passes adds a piece',
    ],
    notes: [
      'The first component is delivered. The intake gate, right under the Head Office.',
      'Five chutes: business goals; leadership direction; user feedback; telemetry and incidents; market and regulation.',
      'Watch the amber pipes. Goals and direction pour straight out of the Head Office into their funnels; direction never travels far.',
      'Read the labels. A Sev-2, an NPS dip, a CPS 230 update. Real inputs, arriving at a steady pace.',
      'And each input starts a PRODUCT. A base plate on the belt. Every layer it passes will add a piece. By the dock it will be a whole thing.',
    ],
    cam: { pos: [6, 30, 8], target: [-2, 9, -21] },
  },
  {
    act: 2, accent: C.exp, kicker: 'Experience Layer',
    title: 'Three ways in',
    bullets: [
      'IDE: an engineer and their agent, terminal and editor',
      'Portal: everyone else, through a browser',
      'Autonomous: nobody. The incident routes straight to an agent.',
      'If only engineers have a way in, you automated a team, not an SDLC',
    ],
    notes: [
      'The collector belt feeds three cells, three very different ways in. Look at the screens, not at me.',
      'IDE: an engineer, shorts and t-shirt, living in an editor with their agent.',
      'Portal: a BA, a PM, security, design; the suit. Same factory through a browser.',
      'Autonomous: nobody. An incident arrives and an agent picks it up. Agent to agent.',
      'If only engineers have a way in, you automated a team, not an SDLC.',
    ],
    cam: { pos: [0, 17, 21], target: [0, 1.2, -9] },
  },
  {
    act: 2, accent: C.life, kicker: 'Lifecycle Configuration',
    title: 'Inside the Head Office',
    bullets: [
      'The way of working is decided here: lifecycle profiles, role playbooks, outcome definitions, the mandatory baseline',
      'The wall rack is the component catalog: workflow blocks, skills, templates, connectors. Unique to the org.',
      'Catalog blocks chain into whole team workflows; the assembly happens next door in the foundry',
    ],
    notes: [
      'Up to the top level, into the Head Office. The catalog just arrived on the wall.',
      'This is where the way of working is decided: lifecycle profiles per domain, role playbooks, outcome definitions written before work starts, the mandatory baseline every initiative meets.',
      'The wall rack is the component catalog: workflow blocks, skills, templates, connectors. Unique to the org. Where the catalog is stocked from, we will see when we leave the plant.',
      'These blocks are not settings to toggle. They chain into whole team workflows, and that assembly happens next door.',
    ],
    cam: { pos: [-38, 18, -7], target: [-15, 15, -28] },
  },
  {
    act: 2, accent: C.life, kicker: 'At the Workflow Foundry',
    title: 'The Meta Workflow',
    bullets: [
      '"The workflow that builds your workflows"',
      'Every team composes its own shape from the same catalog blocks: a line, a branch, a gated loop',
      'Teams stop inheriting process by accident; each workflow is assembled, versioned, owned',
      'An agent can only drive a workflow that is explicitly described',
    ],
    substeps: 5,
    subLabels: ['The foundry', 'Product team', 'Data team', 'Platform team', 'Choose one'],
    onSubstep: (world, sub) => world.setMetaState(8, sub),
    subCams: { 4: { pos: [40, 38, 26], target: [10, 7, -13] } },
    notes: [
      'Beside the Head Office on the top level stands the Workflow Foundry, a factory whose only product is workflows. Its name is The Meta Workflow, the workflow that builds your workflows.',
      '(Press) A product team’s workflow assembles, a clean line from Define to Measure.',
      '(Press) A data team’s BRANCHES, parallel model and eval paths that merge before publish.',
      '(Press) A platform team’s is a gated LOOP, heavy verify and release gates, and work that cycles back.',
      'Same catalog blocks. Visibly different shapes. That is the point of the foundry: each team’s workflow is assembled and owned on purpose, instead of accreting by accident.',
      '(Press) the Head Office chooses one for our factory; it flies down from the top level and lays itself out where our line will stand.',
      'Because an agent can only drive a workflow that is explicitly described. Next, watch it become the line.',
    ],
    cam: { pos: [10, 34, 1], target: [7, 13.5, -27] },
  },
  {
    act: 2, accent: C.sdlc, kicker: 'Self-Continuous SDLC',
    title: 'The line, built from the chosen workflow',
    bullets: [
      'Define · Design · Build · Verify · Release · Operate · Measure',
      'Every station leaves an explicit, checkable artifact: acceptance criteria, ADRs, evals, gates',
      'Verify needs evaluation criteria for agent output, not just green CI',
    ],
    substeps: 7,
    subLabels: ['Define', 'Design', 'Build', 'Verify', 'Release', 'Operate', 'Measure'],
    onSubstep: (world, sub) => world.setStationCount(sub + 1),
    notes: [
      'Back at our factory. The chosen workflow is laid out on the floor, and each block becomes a station ROOM. (One per press.)',
      'Define: intent and acceptance criteria, machine-readable enough to verify against.',
      'Design: architecture, ADRs, patterns from a catalog. Build: implementation against explicit rules.',
      'Verify: tests plus evals; agent output needs evaluation criteria, not just green CI.',
      'Release: standard templates, gates wired in. Operate: run, trace, escalate.',
      'Measure: adoption, impact, demand. An input source, not reporting theatre.',
      'Watch a product. It stops at each window, the room adds its piece, and it moves on. People and agents are already inside; we meet them in a minute.',
    ],
    cam: { pos: [0, 20, 34], target: [0, 3, -1] },
  },
  {
    act: 2, accent: C.sdlc, kicker: 'The phrase that matters',
    title: 'The loop',
    bullets: [
      'The return conveyor carries Measure back into Define',
      'What you measure after shipping becomes what you define next',
      'AI-assisted means humans drive every step, slightly faster. Self-continuous means the system carries the work and humans govern it.',
    ],
    notes: [
      'Watch the return conveyor. Measure feeds Define.',
      'Now the journey is complete. An input starts a product, the cells route it, every room adds a piece, and a FINISHED product ships out the dock. And the measurements ride back to the intake as new inputs.',
      'Most orgs run a pipeline that ends. This line feeds itself.',
      'AI-assisted means humans drive every step slightly faster. Self-continuous means the system carries work between stages and humans govern it.',
    ],
    cam: { pos: [14, 24, 30], target: [0, 2, 3] },
  },
  {
    act: 3, accent: C.agent, kicker: 'Agent Layer',
    title: 'The occupants',
    bullets: [
      'Define holds only people; judgment and intent live there',
      'Build, Release, and Operate hold only agents, work that runs unattended',
      'Design, Verify, and Measure are mixed; a human signs off with an agent beside them',
      'The mix per room is a CHOICE, set by workflow type and maturity, not an accident',
    ],
    notes: [
      'Who actually runs this line? Look inside the rooms.',
      'One room holds only people. Define, where judgment and intent live.',
      'Some rooms hold only agents. Build, Release, Operate; work that runs unattended.',
      'Some rooms are mixed. Design, Verify, and Measure, where a human signs off with an agent beside them. Decision rules, made visible.',
      'On the open floor, cloud agents roam, and specialists (reviewer, evaluator) compose into flows.',
      'The people-to-agent mix per room is a CHOICE, set by workflow type and maturity, not an accident.',
    ],
    cam: { pos: [22, 10, 22], target: [-10, 1.5, -3] },
  },
  {
    act: 3, accent: C.ink, kicker: 'The Foundation',
    title: 'Under the floor',
    bullets: [
      'Four foundation layers: capability, standards & patterns, integration, knowledge',
      'Shared services every stage draws on, not per-team copies',
      'The layers feed each other: skills use standards, integrations ground on knowledge',
    ],
    notes: [
      'Everything the workforce reaches for is down here: four layers. Capability, standards, integration, knowledge.',
      'Each layer runs a trunk into the central spine, and risers carry it up into every room. Shared services every stage draws on, not per-team copies.',
      'Watch the pulses climbing. When an agent on the floor looks effortless, it is because one of these layers answered.',
      '(Camera dives.) We take them one at a time.',
    ],
    cam: { pos: [-26, -2, 32], target: [0, -7, -2] },
  },
  {
    act: 3, accent: C.cap, kicker: 'Capability Layer',
    title: 'The toolkits',
    bullets: [
      'What agents know how to do, the verbs of the factory',
      'Skills · playbooks · agent instructions, each tapped into the network',
      'Versioned, reviewed, discoverable. Like production code.',
      'They sync with the Catalog Marketplace; we get there soon',
    ],
    notes: [
      'What agents know how to do. The verbs.',
      'Skills, playbooks, agent instructions. Each rack taps into the green trunk; watch its pulses climb to the rooms above.',
      'Treat them like production code: versioned, reviewed, discoverable.',
      'A prompt in someone’s notes app is not a capability. And these racks will sync with the Catalog Marketplace later; hold that thought.',
    ],
    cam: { pos: [0, -4, 14], target: [0, -10, -7.5] },
  },
  {
    act: 3, accent: C.std, kicker: 'Standards & Patterns',
    title: 'The Pattern Shop',
    bullets: [
      'Master patterns on stands: code, deploy, architecture, evaluation',
      'The press stamps identical copies. That is what a standard is.',
      'Wired into the toolkits, because skills USE the patterns',
      'Published as artifacts. Tribal knowledge is invisible to an agent.',
    ],
    notes: [
      'How good looks. The nouns. This is the Pattern Shop, where the master patterns live.',
      'Four masters on stands: code templates, deployment templates, architecture patterns, evaluation criteria. The press stamps identical copies; everything that comes out has the same shape. That is what a standard is.',
      'See the yellow link. The toolkits next door USE these patterns; skills ground on standards, and both feed the floors above.',
      'Agents use standards by default only if standards exist as artifacts. Tribal knowledge is invisible to an agent.',
    ],
    cam: { pos: [4, -3.3, 30.4], target: [1, -13.5, 9.1] },
  },
  {
    act: 3, accent: C.int, kicker: 'Integration Layer · MCP',
    title: 'The pipes',
    bullets: [
      'Three pipes into one hub on the plant: Context reads, Action writes, Observe reports',
      'Context: read-only grounding · Action: scoped, time-bound · Observe: traces and evals out',
      'An approved menu of connections; every one scoped, audited, revocable',
    ],
    notes: [
      'How agents reach real systems. Three pipes plug into one header hub, and a single main runs through the wall into the spine.',
      'Context: read-only grounding. Action: scoped, time-bound writes. Observe: traces and evals out.',
      'An approved menu beats every team re-discovering integration. Every connection scoped, audited, revocable.',
    ],
    cam: { pos: [22, 6, 32], target: [48, -11, 6] },
  },
  {
    act: 3, accent: C.know, kicker: 'Knowledge Layer',
    title: 'The warehouse',
    bullets: [
      'Code & architecture truth · internal knowledge · process & standards · bounded external docs',
      'Provenance and freshness labels on every shelf',
      'Answers what is true and current once, for every project; wired to the pipes and the toolkits',
    ],
    notes: [
      'What agents are allowed to ground on. The warehouse feeds the cyan trunk into the spine.',
      'Code and architecture truth, internal knowledge bases, process and standards, bounded external docs.',
      'Every shelf has provenance and freshness labels.',
      'And see the cross-links. Knowledge feeds the pipes and the toolkits; answer what is true and current once, not per project.',
    ],
    cam: { pos: [-36, -1, 22], target: [-56, -8, 0] },
  },
  {
    act: 4, accent: C.dist, kicker: 'Distribution',
    title: 'The Catalog Marketplace',
    bullets: [
      'One Catalog Marketplace serves MANY factories; ours is just one plant on its spokes',
      'Imports arrive from the internet, vendors, other plants; proven components flow back out',
      'The Head Office CONSUMES from it: components land in our catalog, and the catalog feeds the foundry',
      'One good plant is a pilot. Components moving between plants is an operating model.',
    ],
    notes: [
      'Zoom out. The Catalog Marketplace stands on neutral ground, between our plant and the others. It does not belong to us.',
      'One Catalog Marketplace, many factories. Watch the drones; spokes run to every plant on the horizon, and ours is just one of them.',
      'Imports arrive from the internet, from vendors, from other factories. Proven components flow back out.',
      'The supply main under the wall feeds the toolkit racks in our basement. That is the sync I promised earlier.',
      'And our Head Office CONSUMES from it. The Catalog Marketplace stocks our component catalog, and the catalog feeds the foundry. The workflow blocks you saw composing earlier? This is where they come from.',
      'One good plant is a pilot. Components moving between plants is an operating model.',
    ],
    cam: { pos: [36, 52, -18], target: [-58, 2, -76] },
  },
  {
    act: 4, accent: C.infra, kicker: 'Infrastructure',
    title: 'The structure itself',
    bullets: [
      'CI/CD, agent runtime, data pipelines, compute & hosting: you already own all four',
      'The slab and columns · the belts · the machine room · the wires',
      'The BOM claims what you already own. It replaces nothing.',
    ],
    substeps: 4,
    subLabels: ['Compute & hosting', 'CI/CD pipelines', 'Agent runtime', 'Data pipeline'],
    chipMode: 'single',
    onSubstep: (world, sub) => world.setInfraFocus(sub),
    notes: [
      '(One press per system; everything else dims.)',
      'Compute and hosting: the slab and columns the whole plant stands on.',
      'CI/CD pipelines: the belts themselves. The pipelines ARE the conveyors you have been watching.',
      'Agent runtime: the machine room in the basement.',
      'Data pipeline: the wires and trunks carrying every signal.',
      'The BOM claims existing infrastructure; it does not replace it. If a plan starts with first-we-replatform, be suspicious.',
    ],
    cam: { pos: [-34, 8, 42], target: [0, -5, -2] },
  },
  {
    act: 5, accent: C.gov, kicker: 'Cross-cutting · Governance',
    title: 'The scanners',
    bullets: [
      'Access control: who, or which agent, can do what, where, for how long',
      'Quality gates between stations · decision rules for human sign-off · recorded, replayable audit',
      'Embedded at every stage, not a checkpoint at the end; it is what lets you say yes to autonomy',
    ],
    notes: [
      '(Red arches snap on everywhere at once: stations, cells, intake, pipes.)',
      'Access control: who or which agent can do what, where, for how long.',
      'Quality gates between stations; decision rules for human sign-off; audit, recorded and replayable.',
      'Governance is a field over the whole plant, not a checkpoint at the end. It is what lets you say yes to autonomy, not the thing that says no.',
    ],
    cam: { pos: [0, 26, 40], target: [0, 4, -2] },
  },
  {
    act: 5, accent: C.meas, kicker: 'Cross-cutting · Measurement',
    title: 'The sensors',
    bullets: [
      'Adoption · impact · outcome validation · demand signals',
      'Those numbers ride back to the intake as next quarter’s inputs',
      'Without this line the factory is AI-assisted. With it, self-continuous.',
    ],
    notes: [
      '(Green threads converge, then the feed line runs back to intake.)',
      'Adoption: who uses which components, with what friction.',
      'Impact: cycle time, quality, cost. Outcome validation against the outcome definition. Demand: where autonomy pays vs where a human is cheaper.',
      'The line back to the intake gate is the whole thesis. Without it, AI-assisted delivery. With it, self-continuous.',
    ],
    cam: { pos: [14, 28, 38], target: [-12, 5, -13] },
  },
  {
    act: 6, accent: C.ink, kicker: 'The shared picture',
    title: 'The full plant',
    bullets: [
      'Eleven components, two systems over the top, one loop',
      'No single component is novel; the leverage is the wiring between them',
      'Most adoption efforts are not missing parts. They are missing the parts list.',
    ],
    notes: [
      '(Slow orbit. Say little. Let it run.)',
      'Eleven components, two systems over the top, one loop. Head Office, Workflow Foundry, Catalog Marketplace, and the plant, all wired together.',
      'No single component here is novel. The leverage is that they are wired together and carry work end to end.',
      'This picture is what most adoption efforts are missing. Not the parts, the parts list.',
    ],
    cam: { pos: [58, 46, 48], target: [2, 2, -14] },
    orbit: true,
  },
  {
    act: 6, accent: C.outcome, kicker: 'Same BOM, three factories',
    title: 'Choose your build',
    bullets: [
      '"We cannot build all that." Correct. You should not.',
      'Same Head Office, same catalog, three different factories',
      'Components re-light per profile, AND the people-to-agent mix inside the rooms changes',
      'Every box considered, even if the decision is one file',
    ],
    substeps: 4,
    subLabels: ['Full BOM', 'Garage Startup', 'Scale-up', 'Regulated Enterprise'],
    chipMode: 'single',
    profiles: [null, 'startup', 'scaleup', 'enterprise'],
    notes: [
      'The obvious objection is that we cannot build all that. Correct. You should not.',
      '(Start on Full BOM: everything lit.) This is the complete parts list. Now watch what different orgs actually build from it.',
      'Same Head Office, same catalog, three different factories. Watch the components AND who is inside the rooms.',
      '(Select Garage Startup.) A simple line, people in most rooms with one agent helping. A coding agent, a slim skills folder, one pipe, one metric. Everything else a ghost, but every box considered; most implemented as a file, not a platform.',
      '(Select Scale-up.) The line fully lit, foundation at medium depth, agents in most rooms, governance on the risky pipes.',
      '(Select Regulated Enterprise, e.g. APRA-regulated.) The whole plant. Agent-heavy rooms with humans at the gates, multiple cells, full scanners, audit, evals, end-to-end sensors.',
      'The BOM is the same for everyone; the build is not, and neither is the mix of people and agents.',
    ],
    cam: { pos: [48, 52, 56], target: [2, 2, -10] },
  },
  {
    act: 6, accent: C.outcome, kicker: 'Close',
    title: 'The missing picture',
    bullets: [
      'Adopting tools is not the same as rebuilding the SDLC around agents',
      'Take the parts list home. Decide every component’s depth deliberately, even if it is "one file".',
      'Compose your Meta Workflow deliberately, instead of letting it accrete',
      'Roman Gurevitch · Mantel · linkedin.com/in/roman-gurevitch-781220aa',
    ],
    notes: [
      'You have just watched the whole picture assemble. Here is what to take home.',
      'Take the parts list home. Hold your org against it. Decide each component’s depth deliberately, even if the decision is one file.',
      'And compose your Meta Workflow deliberately. Decide how your teams’ workflows are built instead of letting them accrete.',
      'That is the difference between adopting tools and rebuilding the SDLC around agentic capability.',
      '(Thanks; name, Mantel, LinkedIn. Questions.)',
    ],
    cam: { pos: [-10, 10, 46], target: [0, 2, 20] },
  },
];
